# Generated by Django 4.1.3 on 2022-12-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_contributor_project_alter_contributor_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['created_time']},
        ),
    ]
